### ISSUE TITLE
Checkout my old letsplay course format (Moodle 1.9)

### ISSUE THREAD

**Issue by nadavkav** [xow/moodle-format_rpg#14]
Cool course format!

Maybe the following code will be useful too...
Please checkout my old letplay Moodle 1.9 course format.
https://github.com/nadavkav/RTL-BIDI-Hebrew-Moodle-Plugins/tree/master/course/format/letsplay
And a video that show it in action:
http://champions1000.blogspot.co.il/2011/11/blog-post_15.html

It's a scroller game type.
Each Gem is linked into a Moodle activity.
We used it for K12

It's been a while and if you find it useful...
You'll have to refactor it to work in Moodle 2.x

**Comment by xow** [comment]
Awesome! Similar kind of style to what we are going for.

We'd also like to integrate some of the modules directly into the gameplay.

Not sure when/if we will continue work on this (hopefully a project week some time)

**Comment by nadavkav** [comment]
Sweet!
If I'll get any progress on my side, I will sure let you know :-)

**Comment by xow** [comment]
Great! Moodle gamification is always interesting to work on :)
